### ISSUE TITLE
Issue n°3 movement bug

### ISSUE THREAD

**Issue by Gael-MALVAR** [algosup/2023-2024-project-2-x86-retrogaming-team-2#19]
**Date :** 
- 12/11/2023

**Description :** 
- With the 12/11/2023 version, when the player moves and attempts to change direction near a new path, the player stops and cannot move anymore.

**Action performed :** 
- Tried to move in a different direction near a new path

**Expected result :** 
- The player can continue to move

**Actual result :** 
- The player stops and can no longer move

https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-2/assets/146000851/17608162-b495-465b-bf8a-489793794fff

**Comment by MathiasGagnepain** [comment]
Fixed on Release 1.0
